spring.application.name=appSchoolEvent

#spring.datasource.url=jdbc:mariadb://localhost:3306/schoolevent
#spring.datasource.username=root
#spring.datasource.password=1234


spring.datasource.url=jdbc:postgresql://dpg-d5sajdnfte5s73combt0-a.frankfurt-postgres.render.com:5432/schoolevent
spring.datasource.username=schoolevent_user
spring.datasource.password=EVBvCzKW7SFf9HU16jFqUL31NqmFmZNn

